# Uncomment this line to define a global platform for your project
# platform :ios, '11.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  # use_frameworks!
  # use_modular_headers!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  #1.GroMoreSDK核心库
  pod 'Ads-Mediation-CN', :path=>'Frameworks/Ads-Mediation-CN'
  # 2.GroMore官方适配adapter（请以接入文档0.3说明为准，请不要更换GroMoreSDK不支持的三方sdk版本）
  # 穿山甲
  pod 'ABUAdCsjAdapter', :path=>'Frameworks/ABUAdCsjAdapter/'
  pod 'Ads-CN','4.9.0.6'
  # 穿山甲beta灰度版
  #pod 'Ads-CN-Beta', '3.8.0.0'
  # 广点通/优量汇
  pod 'ABUAdGdtAdapter', :path=>'Frameworks/ABUAdGdtAdapter'
  pod 'GDTMobSDK','4.14.02'
  # 百度SDK
#  pod 'ABUAdBaiduAdapter', :path=>'Frameworks/ABUAdBaiduAdapter'
#  pod 'BaiduMobAdSDK', '4.901'
  # UnityAds
#  pod 'ABUAdUnityAdapter', :path=>'Frameworks/ABUAdUnityAdapter'
#  pod 'UnityAds', '4.3.0'
  # Admob/GoogleAd
#  pod 'ABUAdAdmobAdapter', :path=>'Frameworks/ABUAdAdmobAdapter'
#  pod 'Google-Mobile-Ads-SDK', '9.9.0'
  # SigmobAd
#  pod 'ABUAdSigmobAdapter', :path=>'Frameworks/ABUAdSigmobAdapter'
#  pod 'SigmobAd-iOS', '4.3.0'
  # MintegralAdSDK
#  pod 'ABUAdMintegralAdapter', :path=>'Frameworks/ABUAdMintegralAdapter'
  # MintegralAdSDK 使用时请务必使用cocoapod源
  # pod 'MintegralAdSDK', '7.1.9.0', :subspecs => [
  # 'SplashAd',
  # 'InterstitialAd',
  # 'NewInterstitialAd',
  # 'InterstitialVideoAd',
  # 'RewardVideoAd',
  # 'NativeAd',
  # 'NativeAdvancedAd',
  # 'BannerAd',
  # 'BidNativeAd',
  # 'BidNewInterstitialAd',
  # 'BidInterstitialVideoAd',
  # 'BidRewardVideoAd'
  # ]
  #  pod 'ABUAdKlevinAdapter', :path=>'Frameworks/ABUAdKlevinAdapter'
  #  pod 'KlevinAdSDK', '2.9.1.207'
  # 快手
#  pod 'KSAdSDK'
  # 调试
#  pod 'ABUVisualDebug', :path=>'Frameworks/ABUVisualDebug'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
